export const AMOY_CHAIN_ID = 80002;
export const AMOY_CHAIN_HEX = '0x13882';
export const AMOY_EXPLORER = 'https://amoy.polygonscan.com';
export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000';
export const EVENT_METADATA_SCHEMA = 'mini-galaxy-pv-v2/event-metadata@1';

export const EVENT_STATUS = Object.freeze({
  SNAPSHOT_PENDING: 'SNAPSHOT_PENDING',
  SNAPSHOT_RUNNING: 'SNAPSHOT_RUNNING',
  SNAPSHOT_READY: 'SNAPSHOT_READY',
  DEPLOYMENT_QUEUED: 'DEPLOYMENT_QUEUED',
  DEPLOYING: 'DEPLOYING',
  SCHEDULED: 'SCHEDULED',
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  FAILED: 'FAILED',
});

export const AUTHENTICITY_CLAIM = Object.freeze({
  COMMUNITY: 'COMMUNITY',
  ISSUER_AUTHORIZED: 'ISSUER_AUTHORIZED',
});

export const AUTHENTICITY_STATUS = Object.freeze({
  COMMUNITY: 'COMMUNITY',
  SELF_CLAIMED: 'SELF_CLAIMED',
  TOKEN_OWNER_VERIFIED: 'TOKEN_OWNER_VERIFIED',
  PLATFORM_VERIFIED: 'PLATFORM_VERIFIED',
});

export const DISCOVERY_MODE = Object.freeze({
  PUBLIC_ELIGIBLE: 'PUBLIC_ELIGIBLE',
  SUBSCRIBERS_ONLY: 'SUBSCRIBERS_ONLY',
  DIRECT_LINK: 'DIRECT_LINK',
});

export const SNAP_DELIVERY_MODE = Object.freeze({
  DISABLED: 'DISABLED',
  ELIGIBLE: 'ELIGIBLE',
  SUBSCRIBERS_ONLY: 'SUBSCRIBERS_ONLY',
});

export const COMMUNICATION_CATEGORY = Object.freeze({
  EVENT_ANNOUNCEMENT: 'EVENT_ANNOUNCEMENT',
  VOTING_OPEN: 'VOTING_OPEN',
  DEADLINE_REMINDER: 'DEADLINE_REMINDER',
  DOCUMENT_UPDATE: 'DOCUMENT_UPDATE',
  RESULTS_AVAILABLE: 'RESULTS_AVAILABLE',
  GENERAL: 'GENERAL',
});

export const COMMUNICATION_AUDIENCE = Object.freeze({
  ALL_ELIGIBLE: 'ALL_ELIGIBLE',
  NOT_VOTED: 'NOT_VOTED',
  SUBSCRIBERS: 'SUBSCRIBERS',
});
